import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { buildDeck } from "../src/engine/cards";
import { enumerateNextCardOutcomes } from "../src/engine/enumerator";
import type { HandCategory } from "../src/engine/handEvaluator";
import { createSeededRandom, shuffle } from "../src/prompts/seededRandom";
import type { OddsPrompt } from "../src/prompts/types";

const SAMPLE_COUNT = 100_000;
const OUTPUT_PATH = resolve("src/prompts/commonWinChanceOptions.ts");

const USEFUL_TARGETS: HandCategory[] = [
  "pair",
  "two-pair",
  "trips",
  "straight",
  "flush",
  "full-house",
];

const counts = new Map<number, number>();

for (let index = 0; index < SAMPLE_COUNT; index += 1) {
  const prompt = buildSimulationPrompt(`common-win-chance-${index}`);
  const result = enumerateNextCardOutcomes(prompt);

  if (result.win === 0) {
    continue;
  }

  const percent = Math.round(result.winProbability * 100);
  counts.set(percent, (counts.get(percent) ?? 0) + 1);
}

const rankedObservedPercents = [...counts.entries()]
  .sort(([leftPercent, leftCount], [rightPercent, rightCount]) => {
    if (rightCount !== leftCount) {
      return rightCount - leftCount;
    }

    return leftPercent - rightPercent;
  })
  .map(([percent]) => percent);

const probabilities = rankedObservedPercents.map((percent) => Number((percent / 100).toFixed(2)));

const file = `// Generated by scripts/generate-common-win-chance-options.ts
// All observed non-zero win chance percents, ranked from ${SAMPLE_COUNT.toLocaleString("en-US")} deterministic odds prompt simulations.
export const COMMON_WIN_CHANCE_OPTIONS: readonly number[] = ${JSON.stringify(probabilities, null, 2)};
`;

writeFileSync(OUTPUT_PATH, file);

console.log(`Wrote ${probabilities.length} win chance options to ${OUTPUT_PATH}`);

function buildSimulationPrompt(seed: string): OddsPrompt {
  const random = createSeededRandom(seed);
  const cards = shuffle(buildDeck(), `${seed}:cards`);
  const boardLength = random() < 0.5 ? 4 : 3;

  return {
    mode: "odds",
    hero: cards.slice(0, 2),
    board: cards.slice(2, 2 + boardLength),
    target: USEFUL_TARGETS[Math.floor(random() * USEFUL_TARGETS.length)],
    seed,
  };
}
